version: 2
build:
  image: latest
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
sphinx:
  configuration: docs/conf.py
python:
  version: 3.8
  install:
  - method: pip
    path: .
    extra_requirements:
    - doc

